# Token限制配置
# 包含原系统中实际存在的Token限制参数

llm_cleaning:
  # LLM清洗配置 (从llm_cleaner.py提取)
  check_tokens: 1000       # 检查token数量 (llm_cleaner.py:107)
  clean_tokens: 4000       # 清洗token数量 (llm_cleaner.py:233,338)

qa_processing:
  # 问答处理配置 (从qa_compactor.py和qa_extractor.py提取)
  extraction_tokens: 32768 # 问答抽取token数量 (qa_extractor.py:159)
  compaction_tokens: 32768 # 问答压缩token数量 (qa_compactor.py:133,802)